### ISSUE TITLE
doesn't work with vibration toys

### ISSUE THREAD

**Issue by srsm0ke** [Nootna8/SDTButtplug#1]
lovense hush or edge doesnt work. It connects to the toy, but nothing happens.

**Comment by Nootna8** [comment]
Currently only linear moves are supported. A vibration rule should be easy to add, don't have any of those devices to test. Would it just vibrate when there's movement?

**Comment by srsm0ke** [comment]
Usually what it does is variate vibration level.
Per example, Scriptplayer makes vibrate at maximum when the script its in the lower position, and vibrates at minimum when its at higher position.
Maybe you can test it with a gamepad, buttplug.io supports xbox gamepad.

**Comment by yuzu1** [comment]
I have a max 2 and it doesn't vibrate either, albeit I am pretty new at modding this game, but I think I got everything right. Top right says connected and then right under that I get a "SDTButtplug: device update" also in green text. In intiface it says connected to SDT, but no vibrations.

**Comment by Nootna8** [comment]
> I have a max 2 and it doesn't vibrate either, albeit I am pretty new at modding this game, but I think I got everything right. Top right says connected and then right under that I get a "SDTButtplug: device update" also in green text. In intiface it says connected to SDT, but no vibrations.



> I have a max 2 and it doesn't vibrate either, albeit I am pretty new at modding this game, but I think I got everything right. Top right says connected and then right under that I get a "SDTButtplug: device update" also in green text. In intiface it says connected to SDT, but no vibrations.

I haven't been able to add vibration support yet. I do have an xbox 360 controller I should be able to test with. If you're feeling up to it you can edit the .as file, then make a new .swf by running the compile script.

See VibrateCmd at https://buttplug-spec.docs.buttplug.io/generic.html#stopalldevices

**Comment by Nootna8** [comment]
Support added :)
